# Generated by Django 5.0.3 on 2024-03-29 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sig', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=9, verbose_name='Código')),
                ('nome', models.TextField(verbose_name='Nome')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sig.sigcampus')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoEntidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, verbose_name='Código')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.entidade')),
                ('tipo_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.tipocodigo')),
            ],
        ),
    ]
