# Generated by Django 5.0.3 on 2024-03-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='campus',
            field=models.PositiveBigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
