# Generated by Django 5.0.3 on 2024-04-09 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incentivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_presente.tipociclo')),
            ],
        ),
        migrations.CreateModel(
            name='InconsistenciaCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField()),
                ('etapa', models.CharField(max_length=2)),
                ('situacao', models.CharField(max_length=12)),
                ('descricao', models.TextField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_presente.ciclo')),
            ],
            options={
                'unique_together': {('cpf', 'etapa', 'ciclo')},
            },
        ),
    ]
