# Generated by Django 5.0.3 on 2024-04-09 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_presente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='incentivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gestao_presente.incentivo'),
            preserve_default=False,
        ),
    ]
