# Generated by Django 5.0.3 on 2024-04-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_presente', '0003_ciclo_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inconsistenciaciclo',
            name='cpf',
            field=models.CharField(db_index=True, max_length=11),
        ),
    ]
